@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name":"John Doe",
    "email":"john2@example.com",
    "password": "123456"
}
###

# @name authenticate
POST  {{baseUrl}}/sessions
Content-Type: application/json

{
    "email":"john@example.com",
    "password": "123456"
}
###

# @name create_question
POST  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title":"Question 2 title *@#D",
    "content": "Some Question Content"
}
###

# @name fetch_recent_questions
GET  {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

