@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name":"John Doe",
    "email":"john32@example.com",
    "password": "123456"
}
###

# @name authenticate
POST  {{baseUrl}}/sessions
Content-Type: application/json

{
    "email":"john32@example.com",
    "password": "123456"
}
###

# @name create_question
POST  {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title":"Question 2 title *@#D",
    "content": "Some Question Content"
}
###

# @name fetch_recent_questions
GET  {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name upload_attachments
POST {{baseUrl}}/attachments
Content-Type: multipart/form-data;  boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: Bearer {{authToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample-uppload.jpeg"
Content-Type: image/jpeg

< ./test/e2e/sample-uppload.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--